02-docker Orita answer
rymizuki/study-php pull request #2
Opened 2019-11-27 09:31 UTC by orikazu

02-dockerに回答しました。

2019-11-27 09:49 UTC, rymizuki requested changes
01の回答が混ざっているぞ。意図している？｀
ちょいと伝わりにくい日本語だったので少し整理してより具体的に記載してもらえるといいね。

2019-11-27 09:49 UTC, rymizuki commented on 01-docker/02-docker-run-php-with-volume/answer
> +...... --rm までは前回同様。
`......` これは一体...

2019-11-27 09:49 UTC, rymizuki commented on 01-docker/02-docker-run-php-with-volume/answer
> +...... --rm までは前回同様。
`--rm` みたいにバッククォートで囲うとハイライトできるよ。オプションやコードの表記を文中で表現するときはこれを使うと良い

2019-11-27 09:49 UTC, rymizuki commented on 01-docker/02-docker-run-php-with-volume/answer
> +-v以降で、current directoryを"/usr/local/docker"という名前で、
> "/usr/local/docker"

これも `/usr/local/docker` か `_/usr/local/docker_` みたいに文字装飾を使うと良い

2019-11-27 09:49 UTC, rymizuki commented on 01-docker/02-docker-run-php-with-volume/answer
> +-v以降で、current directoryを"/usr/local/docker"という名前で、
> -v以降で、current directoryを"/usr/local/docker"という名前で、作成したコンテナ内にvolumeとして登録。

文章表現をもうちょっと丁寧にしてもらえると。

> -v以降で

これが示すのは `$(pwd):/usr/local/docker php:7.3 php /usr/local/docker/src/index.php` なので、項目が広く何がどれに影響しているのか文章から予測できない。

> current directoryを"/usr/local/docker"という名前で、

`current directory` を `/usr/local/docker` に「名前を変更」しているのかな？

> 作成したコンテナ内にvolumeとして登録。

「`/usr/local/docker` という名前で作成したコンテナ」というようにも読める。

2019-11-27 10:02 UTC, orikazu commented on 01-docker/02-docker-run-php-with-volume/answer
> +-v以降で、current directoryを"/usr/local/docker"という名前で、
どこのコマンドの説明をしているのかをもっと具体的にしたいと思います。

2019-11-29 08:43 UTC, rymizuki commented
#3 で修正されたのでこちらはクローズ

2019-11-29 08:43 UTC, closed without merging